branches:
  only:
    - master

sudo: required
services:
  - docker

language: java
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_TAG" != "" ]; then
      docker pull jbonachera/clickcount:$TRAVIS_COMMIT;
      docker tag jbonachera/clickcount:$TRAVIS_COMMIT jbonachera/clickcount:$TRAVIS_TAG;
      docker tag jbonachera/clickcount:$TRAVIS_COMMIT jbonachera/clickcount;
      docker push jbonachera/clickcount:$TRAVIS_TAG;
      docker push jbonachera/clickcount;
      IMAGE=jbonachera/clickcount TAG=$TRAVIS_TAG JOB_ID=clickcount scripts/nomad_update.py;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker build -t jbonachera/clickcount:$TRAVIS_COMMIT .;
      docker tag jbonachera/clickcount:$TRAVIS_COMMIT jbonachera/clickcount:dev;
      docker push jbonachera/clickcount:$TRAVIS_COMMIT;
      docker push jbonachera/clickcount:dev;
      IMAGE=jbonachera/clickcount TAG=$TRAVIS_COMMIT JOB_ID=clickcount-dev scripts/nomad_update.py;
    fi
